// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfuubcqrjeuhkmrksqes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdXViY3FyamV1aGttcmtzcWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQ5OTksImV4cCI6MjA2ODgzMDk5OX0.6n9SwXd-LMs0ZAhUw1ztdaKWHtQkRVMjJDqLMPrT3QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});